name: Deploy Prod

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-22.04

    environment: Production
    env:
      READ_PRIVATE_SUBMODULE_TOKEN: ${{ secrets.READ_PRIVATE_SUBMODULE_TOKEN }}

      WORKING_DIRECTORY: ${{ vars.DEPLOY_WORKING_DIRECTORY }}

      DEPLOY_FILENAME: ${{ vars.DEPLOY_FILENAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
          token: ${{ env.READ_PRIVATE_SUBMODULE_TOKEN }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install AWS cli
        run: |
          sudo snap install aws-cli --classic

      - name: Deploy code to AWS S3
        run: |
          zip -r ${{ env.DEPLOY_FILENAME }} appspec.yml app env deploy-script
          aws s3 cp ${{ env.DEPLOY_FILENAME }} s3://stat-ec2-app-code-deploy-bucket/${{ env.DEPLOY_FILENAME }} --region ${{ env.AWS_REGION }}
        working-directory: ${{ env.DEPLOY_WORKING_DIRECTORY }}
